version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80"

packages: [inotify-tools]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"
    - "npm update"
    - 'sudo sed -i "s/^User .*/User user/" /etc/apache2/apache2.conf'


  init:
    - "sudo usermod -u $(stat -c '%u' .kick.yml) user"

  run:
    - "sudo mkdir -p /data"

  dev:

  test:


