version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80"

packages: [inotify-tools]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"
    - "npm update"



  # Run Apache as owner UID of /data/.kick.yml
  init:
    - "sudo mkdir -p /data"
    - "sudo -E usermod -o -u $(stat -c '%u' /data/.kick.yml  || echo $DEV_UID) user"
    - 'sudo sed -i "s/^User .*/User user/" /etc/apache2/apache2.conf'

  run:


  dev:

  test:


